import { useEffect, useRef, useState } from 'react';
import { useNewAddress } from '@/bitcoin-core/components/Wallet/hooks';
import { useWalletStore } from '@/bitcoin-core/useWalletStore';
import { ADDRESS_TYPES } from '@/bitcoin-core/constants';
import QRCode from 'react-qr-code';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { FormNewAddressSchema } from '@/bitcoin-core/model/forms';

export default function WalletReceive() {
  const currentWallet = useWalletStore((s) => s.currentWallet);
  const autoGeneratedKeyRef = useRef<string | null>(null);

  type FormFields = z.infer<typeof FormNewAddressSchema>;

  const [copied, setCopied] = useState(false);
  const [isTypeSelectorOpen, setIsTypeSelectorOpen] = useState(false);
  const { response, isLoading, error: mutError, generate } = useNewAddress();

  const {
    register,
    setError,
    watch,
    formState: { errors /* isSubmitting */ },
  } = useForm<FormFields>({
    defaultValues: {
      addressType: 'bech32',
    },
    resolver: zodResolver(FormNewAddressSchema),
  });

  function select(): React.JSX.Element {
    const listItems = ADDRESS_TYPES.filter(
      ({ value }) => value !== 'invalid-vector'
    ).map(({ value, label }) => (
      <option key={value} value={value}>
        {label}
      </option>
    ));
    return (
      <div className="relative">
        <select
          {...register('addressType')}
          className="core-input w-full appearance-none rounded-2xl px-4 py-3 pr-12 text-sm font-medium text-white focus:outline-none"
        >
          {listItems}
        </select>
        <span className="pointer-events-none absolute inset-y-0 right-0 flex w-12 items-center justify-center text-cyan-100/75">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            className="h-4 w-4"
            aria-hidden="true"
          >
            <path
              fillRule="evenodd"
              d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.512a.75.75 0 01-1.08 0L5.21 8.27a.75.75 0 01.02-1.06z"
              clipRule="evenodd"
            />
          </svg>
        </span>
      </div>
    );
  }

  const selectedAddressType = watch('addressType');

  useEffect(() => {
    if (!currentWallet || !selectedAddressType || isLoading) {
      return;
    }

    const generationKey = `${currentWallet}:${selectedAddressType}`;

    if (autoGeneratedKeyRef.current === generationKey) {
      return;
    }

    autoGeneratedKeyRef.current = generationKey;

    void (async () => {
      try {
        await generate(selectedAddressType);
      } catch (error) {
        setError('root', {
          message: `${(error as Error).message}. Please try again.`,
        });
      }
    })();
  }, [currentWallet, generate, isLoading, selectedAddressType, setError]);

  return (
    <div className="min-h-screen w-full">
      <div className="mx-auto flex max-w-md items-center justify-center px-4 py-10">
        <div className="core-surface w-full rounded-3xl p-6 text-white shadow-lg">
          <div className={'pb-3 text-base font-semibold'}>Receive bitcoin</div>
          <p className="text-sm leading-6 text-gray-300">
            A new{' '}
            <span className="font-semibold text-cyan-100">native SegWit</span>{' '}
            address is generated automatically when this screen opens.
          </p>
          <div>
            <div className="mt-4 rounded-2xl border border-white/8 bg-white/4 p-3">
              <button
                type="button"
                onClick={() => setIsTypeSelectorOpen((value) => !value)}
                className="flex w-full items-center justify-between gap-3 text-left text-sm font-medium text-gray-200"
                aria-expanded={isTypeSelectorOpen}
              >
                <span>Need a different address format?</span>
                <span className="text-cyan-100/80">
                  {isTypeSelectorOpen ? 'Hide' : 'Change'}
                </span>
              </button>

              {isTypeSelectorOpen ? (
                <div className="mt-3 border-t border-white/8 pt-3">
                  <div className="mb-2">{select()}</div>
                  <div className="text-xs text-gray-400">
                    Changing the format regenerates the address and QR code
                    automatically.
                  </div>
                </div>
              ) : null}
            </div>
            {errors.addressType && (
              <div className="mt-2 text-xs text-red-300">
                {errors.addressType.message?.toString()}
              </div>
            )}
            {errors.root && (
              <div className="mt-2 text-xs text-red-300">
                {errors.root.message?.toString()}
              </div>
            )}
          </div>

          {currentWallet === null && (
            <div className="mt-3 text-xs text-yellow-300">
              Connect or select a wallet to generate a receiving address.
            </div>
          )}

          {mutError && (
            <div className="mt-4 rounded border border-red-700 bg-red-900/30 p-3 text-sm text-red-200">
              Failed to generate address. {String(mutError.message)}
            </div>
          )}
          {response !== null && response.error && (
            <div className="mt-4 rounded border border-red-700 bg-red-900/30 p-3 text-sm text-red-200">
              Failed to generate address.{' '}
              {String(response.error !== null ? response.error?.message : '')}
            </div>
          )}
          {response !== null && response.result && (
            <div className="mt-5">
              <div className="mb-3 inline-flex items-center rounded-full border border-cyan-300/18 bg-cyan-400/10 px-3 py-1 text-[11px] font-semibold tracking-[0.18em] text-cyan-100/85 uppercase">
                {selectedAddressType === 'bech32'
                  ? 'Native SegWit'
                  : selectedAddressType}
              </div>
              <div className="core-panel-muted mb-3 w-full rounded-xl px-3 py-2 font-mono text-sm break-all text-gray-100">
                {response.result}
              </div>
              <div className="inline-block rounded bg-white p-3">
                <QRCode
                  value={response.result}
                  size={160}
                  fgColor="#000000"
                  bgColor="#ffffff"
                />
              </div>
              <div className="mt-3">
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(response.result);
                    setCopied(true);
                    setTimeout(() => setCopied(false), 1500);
                  }}
                  className="core-button-secondary"
                >
                  Copy
                </button>
                {copied && (
                  <span
                    className="ml-2 text-xs text-green-400"
                    aria-live="polite"
                  >
                    Address copied
                  </span>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
